var express = require('express');
var router = express.Router();
module.exports = router;

/* POST (attempt) login */
router.post('/', //first we try the function generated by passport.authenticate 
    // using our local strategy;  
    router.passport.authenticate('local', {successReturnToOrRedirect: '/', failureRedirect: req.baseUrl}),
    // if passport authenticate's function calls next instead of redirecting, the next function is this:
    function (req, res) {
        res.redirect('/');
    });