var express = require('express');
var router = express.Router();
module.exports = router;

/* POST (attempt) login */
router.get('/', function(){//first we try the function generated by passport.authenticate 
    console.log("finally here!");
});